AWSTemplateFormatVersion: 2010-09-09

Description: template file to create VPC network

Parameters:
  Project:
    Type: String    
  Environment:
    Type: String
  CIDRBlock:
    Type: String
Resources: 
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CIDRBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Join [ "-", [!Ref Project, !Ref Environment, 'vpc']]
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment
Outputs:
  VPCId:
    Description: VPC Id of VPC
    Value: !Ref VPC
